Restructure package layout, add minimum required for position list fetching
readium/ts-toolkit pull request #10
Opened 2022-03-23 16:27 UTC by chocolatkey

2022-07-13 13:13 UTC, mickael-menu requested changes

2022-07-13 13:13 UTC, mickael-menu commented on shared/src/fetcher/HttpFetcher.ts
> +  // TODO HttpClient? Is it even necesary when we have fetch()?
Yes probably not in TypeScript.

2022-07-13 13:13 UTC, mickael-menu commented on shared/src/fetcher/Resource.ts
> +  readAsXML(): Promise<XMLDocument | undefined>;
It looks like TypeScript doesn't support default body for interface methods?

If that's the case, and there's no way to add extensions to any `Resource` object, then we can remove these helpers to avoid having to reimplement them for all `Resource` implementations.

Here are some alternatives, what do you think?

* Using an abstract class instead of an `interface` which implement these helpers. Usually resources are their own object and don't implement other interfaces.
* Having free-floating functions like `readAsString(resource)`.

2022-07-13 13:13 UTC, mickael-menu commented on shared/src/publication/Publication.ts
> +  }
We'll need to delegate to a `PositionsService` interface eventually to be able to swap implementations. For example if a server doesn't have a position list, a web reader might generate its own.

However it's not blocking for this PR.

2022-07-26 20:04 UTC, chocolatkey commented on shared/src/fetcher/HttpFetcher.ts
> +  // TODO HttpClient? Is it even necesary when we have fetch()?
I changed my mind, included an option to specify a client. Because in some situations there are people who want e.g. an authorized `fetch`, or a `fetch` that retries things like https://www.npmjs.com/package/fetch-retry

2022-07-26 21:42 UTC, chocolatkey commented on shared/src/fetcher/Resource.ts
> +  readAsXML(): Promise<XMLDocument | undefined>;
I went with the free-floating functions for the go toolkit, as you can see here https://github.com/readium/go-toolkit/blob/master/pkg/fetcher/fetcher_file.go#L209-L221 , it works fine. Do note that in the case of HttpResource, they're intentionally overridden because the native fetch has convenient ways of decoding the response.
So if I were to implement e.g. FileFetcher then I'd add the free-floating functions, but for Http alone they're unecessary

2022-07-26 21:43 UTC, chocolatkey commented on shared/src/publication/Publication.ts
> +  }
Yes, that's the idea. Not implemented yet for simplicity's sake

2022-07-27 07:17 UTC, mickael-menu commented on shared/src/fetcher/Resource.ts
> +  readAsXML(): Promise<XMLDocument | undefined>;
That's fine by me, then can you just remove these functions from the `Resource` interface? Thanks.

2022-07-27 07:32 UTC, chocolatkey commented on shared/src/fetcher/Resource.ts
> +  readAsXML(): Promise<XMLDocument | undefined>;
@mickael-menu So you're 100% sure you want this to be different vs. the go/kotlin/swift toolkits?

2022-07-27 07:42 UTC, mickael-menu commented on shared/src/fetcher/Resource.ts
> +  readAsXML(): Promise<XMLDocument | undefined>;
The most idiomatic solution for the language is the best, so that's fine if it's not a direct translation from the other toolkits. Do you know a good alternative that doesn't require all implementations of `Resource` to reimplement these functions?

2022-07-27 08:27 UTC, chocolatkey commented on shared/src/fetcher/Resource.ts
> +  readAsXML(): Promise<XMLDocument | undefined>;
Personally I'm prioritizing keeping the toolkits similar, because it will (hopefully) make it easier to keep them in sync in the long run. I was suggesting that every `Resource` implementation re-implement it with the stub, like here https://github.com/readium/go-toolkit/blob/master/pkg/fetcher/fetcher_file.go#L210 .
Ultimately though, you are more experienced with the toolkits and their architecture, so if you think it's fine to have this sort of difference it's fine with me too.

2022-07-27 10:20 UTC, mickael-menu commented on shared/src/fetcher/Resource.ts
> +  readAsXML(): Promise<XMLDocument | undefined>;
I agree for the core types and APIs, but the helpers are born from specific platform needs and don't necessarily need to be the same everywhere. So there's not a strong requirement to keep the helpers in sync until the need arise while using the toolkit itself. However, `readAsString/JSON/XML` are all very useful for the web toolkit.

The problem with requiring these helpers in the `Resource` interface is that:

* We will need to update all the implementations if we add a new helper, and this will require a new major semantic version release as it will break custom app implementations.
* This is not [extensible by implementers](https://elizarov.medium.com/extension-oriented-design-13f4f27deaee) wanting to add their own helpers. I'd rather have a way to extend the toolkit that is consistent with internal and third-party extensions.

I think using an abstract class instead of an interface would solve all these problems, as an implementer should be able to use [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) to add more helpers.

Alternatively, if you want to keep the interface, we could add a proxy `HelperResource` class which has all the helpers and can be extended with module augmentation. Then you would use:

```typescript
HelperResource(resource).readAsXML()
```

Or

```typescript
ResourceReader(resource).asXML()
```

2022-07-28 09:07 UTC, chocolatkey commented on shared/src/fetcher/Resource.ts
> +  readAsXML(): Promise<XMLDocument | undefined>;
@mickael-menu how about now? https://github.com/readium/ts-toolkit/pull/10/commits/44d94739ea750f4f86689a8bb6ac76d55eb4feb4

2022-07-28 09:18 UTC, mickael-menu commented on shared/src/fetcher/Resource.ts
> +  readAsXML(): Promise<XMLDocument | undefined>;
Looking good, thank you! Could you take a look at the failed check? Then we can merge if you're fine with it.

2022-07-28 09:28 UTC, chocolatkey commented on shared/src/fetcher/Resource.ts
> +  readAsXML(): Promise<XMLDocument | undefined>;
I'll address that in another PR when I move to yarn workspaces, it's just due to re-arranging of code

2022-07-28 09:28 UTC, merged