Work in progress navigator-html (famously known as glue-js)
readium/ts-toolkit pull request #12
Opened 2022-05-04 13:04 UTC by chocolatkey

2022-05-16 17:12 UTC, mickael-menu commented on navigator-html/src/Loader.ts
> +import { CommsReceiveKey, CommsMessage, COMMS_VERSION } from "./comms";
Following our last call, this module could be named `navigator-html-injectables` or `navigator-html-scripts`

2022-05-16 17:12 UTC, mickael-menu commented on navigator-html/src/comms/comms.ts
> +            if(typeof event.data !== "object") return; // Skip events whose data is not an object
```suggestion
            if(typeof event.data !== "object") return;
```

2022-05-16 17:12 UTC, mickael-menu commented on navigator-html/src/modules/setup/Setup.ts
> +        comms.unregister("set_property", "setup");
Maybe this could be simplified and made safer by automatically unregistering all the events of a given module in the `Loader.removeModule()`?

2022-05-16 17:12 UTC, mickael-menu commented on navigator-html/src/comms/keys.ts
> +
This is basically an implementation of the [Command pattern](https://en.wikipedia.org/wiki/Command_pattern), so to improve clarity I suggest renaming:

* `Send` -> `Event`
* `Receive` -> `Command`

2022-05-16 17:12 UTC, mickael-menu commented on navigator-html/src/comms/comms.ts
> +    public send(key: CommsSendKey, data: unknown, strict: boolean = false, transfer: Transferable[] = []) {
We will need a way to identify a couple command / event when interfacing with the apps.

For example, when calling `go_id()`, we need to know if it was successful or not.

I suggest adding an optional `id` parameter that the app will need to provide to know when an event is related to the command.

2022-05-16 17:12 UTC, mickael-menu commented on navigator-html/src/comms/keys.ts
> +    "remove_property";
It looks like it's very specific to each module. Maybe the module themselves should declare what commands they support. Not sure it would work as a type enum in this case.

2022-05-16 17:12 UTC, mickael-menu commented on navigator-html/src/modules/ReflowablePeripherals.ts
> +        this.comms.send("click", clickEvent);
This will be useful for FXL as well, and maybe other media types, so we can have an `Interaction` module handling drags, taps, clicks, etc.

(We recently needed to add drag interaction support in the Kotlin toolkit, this was used in Aldiko to change the device brightness when dragging vertically on the left edge of the screen: https://github.com/readium/kotlin-toolkit/pull/106/files)

2022-05-16 17:12 UTC, mickael-menu commented on navigator-html/src/modules/setup/Setup.ts
> +        })
These two commands will be used only for reflowable as far as I know. They are related to Readium CSS.

2022-05-16 17:12 UTC, mickael-menu commented on navigator-html/src/modules/snapper/ColumnSnapper.ts
> +        comms.register("go_position", ColumnSnapper.moduleName, (data: unknown) => {
In the legacy glue JS it was called position, but it's ambiguous with the `Locator`'s `position` now.

```suggestion
        comms.register("go_progression", ColumnSnapper.moduleName, (data: unknown) => {
```

2022-05-16 17:12 UTC, mickael-menu commented on navigator-html/src/Loader.ts
> +export class Loader {
We need the `Loader` to be generic over `ModuleName` to allow user to add their own modules.

```suggestion
export class Loader<T> {
```

2022-05-16 17:12 UTC, mickael-menu commented on navigator-html/src/modules/snapper/ColumnSnapper.ts
> +            }
We need to make sure that every command calls a callback so that the native/app side doesn't hang waiting for an command to finish. Even if we return an error, it could be represented as a `Result<x>` that the native/app side handles.

2022-08-17 17:21 UTC, mickael-menu requested changes

2022-08-17 17:21 UTC, mickael-menu commented on navigator-html-injectables/src/Loader.ts
> + * The Module loader. Not really sure what else to say right now
You could mention the object's responsibilities. From what I understand, this one is the entry-point for the `navigator-html-injectables` and manages (mount/unmount) the modules for a single Window object.

2022-08-17 17:21 UTC, mickael-menu commented on navigator-html-injectables/src/Loader.ts
> +                console.warn(`Module "${name} does not exist in the library"`)
Shouldn't this warning be sent with `comms.log`?

2022-08-17 17:21 UTC, mickael-menu commented on navigator-html-injectables/src/Loader.ts
> +        if(!nm.mount(this.wnd, this.comms)) return false; // Mount module
I think there's an opportunity to refactor this into a (for example) `loadModule(name)` function, as it's duplicated from l31:37.

2022-08-17 17:21 UTC, mickael-menu commented on navigator/README.MD
> +A navigator for web platforms based on the readium Navigator spec. Work is primarily based on the [kotlin toolkit](https://github.com/readium/kotlin-toolkit/tree/develop/readium/navigator/src/main/ja
```suggestion
A navigator for web platforms based on the readium Navigator spec. Work is primarily based on the [kotlin toolkit](https://github.com/readium/kotlin-toolkit/tree/develop/readium/navigator/src/main/java/org/readium/r2/navigator), but adapted for the needs of the web. At the moment, this only includes the Reflowable EPUB navigator.
```

2022-08-17 17:21 UTC, mickael-menu commented on navigator-html-injectables/src/comms/keys.ts
> +    "exact_progress";
It looks like it's very specific to each module. Maybe the module themselves should declare what commands they support? Not sure it would work as a type enum in this case.

Same for the events above.

2022-08-17 17:21 UTC, mickael-menu commented on navigator-html-injectables/src/comms/comms.ts
> +                ) return;
Do you think it would be worth sending a warning log in this case? Does it give a hint that the Navigator or app is broken?

2022-08-17 17:21 UTC, mickael-menu commented on navigator-html-injectables/src/modules/Module.ts
> +}
Could you fill in the doc comments for these APIs? Maybe using what you wrote in the PR description, in particular:

> The unmount function should completely clean up any event listeners or active modification of the HTML content, and cease all activity. This is because an implementer should be able to mount and unmount Modules at any time, to, for example, switch reading modes. There should be no difference in behavior after mounting and unmounting a Module many times.

2022-08-17 17:21 UTC, mickael-menu commented on navigator-html-injectables/src/modules/ReflowablePeripherals.ts
> +        }
Comment for a future PR:

This will be useful for FXL as well, and maybe other media types, so we can have an `Interaction` module handling drags, taps, clicks, etc.

(We recently needed to add drag interaction support in the Kotlin toolkit, this was used in Aldiko to change the device brightness when dragging vertically on the left edge of the screen: https://github.com/readium/kotlin-toolkit/pull/106/files)

2022-08-17 17:21 UTC, mickael-menu commented on navigator/src/Navigator.ts
> +    abstract goLink(link: Link, animated: boolean, cb: cbv): void;
These APIs could also fail if, for example, we load a resource whose `href` is not referenced in the manifest.

```suggestion
    abstract go(locator: Locator, animated: boolean, cb: cbb): void;

    /**
     * Moves to the position in the publication targeted by the given link.
     */
    abstract goLink(link: Link, animated: boolean, cb: cbb): void;
```

2022-08-17 17:21 UTC, mickael-menu commented on navigator/src/Navigator.ts
> +     goRight(animated = false, completion: cbv) {
The app might want to fallback on showing the menus when reaching the beginning/end of the publication, in which case the boolean is useful in the callback.

```suggestion
     goLeft(animated = false, completion: cbb) {
        if(this.readingProgression === ReadingProgression.ltr || this.readingProgression === ReadingProgression.ttb || this.readingProgression === ReadingProgression.auto)
            this.goBackward(animated, completion);
        else if(this.readingProgression === ReadingProgression.rtl || this.readingProgression === ReadingProgression.btt)
            this.goForward(animated, completion);
     }

     /**
      * Moves to the right content portion (eg. page) relative to the reading progression direction.
      */
     goRight(animated = false, completion: cbb) {
```

2022-08-17 17:21 UTC, mickael-menu commented on navigator-html-injectables/src/modules/snapper/ColumnSnapper.ts
> +export class ColumnSnapper extends Snapper {
Some of the `go` commands should be in the `JumpToLocation` module, such as `go_text` and `go_id`. `Snapper`'s job is only to scroll+snap the content when requested.

This implies that some modules like `JumpToLocation` might depend on APIs provided by the `Snapper`. Maybe we can use commands/events for this instead of direct access.

It could flow like this:

1. The app calls a `go_x` command in the `JumpToLocation` module.
2. The command computes a target `DOMRect`, then requests the `Snapper` to `snap_to` the target rect (with a command event, or direct function call).
3. The `Snapper` will resolve the target rect to an actual offset, depending on the technique used for the positioning (CSS translation, native scroll, etc.) and the layout nature (paginated, scrolled, RTL, etc.).
4. The `Snapper` will move the viewport to the target offset, with an animation if requested.

2022-08-17 17:21 UTC, mickael-menu commented on navigator/src/epub/frame/FramePoolManager.ts
> +const LOWER_BOUNDARY = 3;
This is fine for now, but it's the kind of stuff an app might want to change. For example with a `Configuration` object passed to the constructor of `EPUBNavigator`.

2022-08-17 17:21 UTC, mickael-menu commented on navigator/src/epub/frame/FramePoolManager.ts
> +export default class FramePoolManager {
I'm a bit confused about the responsibilities for this class. The name tells me that it holds (and helps to reuse) the loaded iframes, but looking at the implementation it also injects Readium CSS and creates elements for bitmap based resources.

Maybe we could improve clarity by delegating the creation of the iframes to individual function factories? For example:

```javascript
function createHtmlPage(link) -> string? {
    if (!link.mediaType.isHtml()) {
        return null;
    }

    ... inject Readium CSS and scripts
}

function createImagePage(link) -> string? {
    if (!link.mediaType.isBitmap()) {
        return nulll;
    ...
}

// When creating a page, the page factories will be tried in order until one returns non-null content.
FramePoolManager(pageFactories: [createHtmlPage, createImagePage])
```

2022-08-17 17:21 UTC, mickael-menu commented on navigator/src/epub/EpubNavigator.ts
> +        // TODO do we let clients go to a resource too? Seems to be the case in kotlin
That's the whole non-linear resources debate 😄 
https://github.com/readium/architecture/discussions/143

For now it's best to prevent it because we need to support it properly to avoid blocking the user or breaking the pagination.

2022-08-17 17:21 UTC, mickael-menu commented on navigator/src/epub/EpubNavigator.ts
> +    public get cframe() {
Maybe we could prefix with an underscore to make it clear that this is an internal API that might be removed in the future?

2022-08-17 17:21 UTC, mickael-menu commented on navigator/src/epub/EpubNavigator.ts
> +    constructor(container: HTMLElement, pub: Publication, listeners: EpubNavigatorListeners, positions: Locator[] = []) {
How is the last reading location restored in the reader? On mobile we usually have an `initialLocator` passed to the navigator constructor.

2022-08-17 17:21 UTC, mickael-menu commented on navigator/src/epub/EpubNavigator.ts
> +                    else if (edata.x > oneQuarter * 3) this.goRight(false, () => { }); // Go right if right quarter clicked
Edge taps to turn pages should be handled in the (test) app. The navigator will just send the tap event.

Each app might want different edge threshold, or even disable this feature for accessibility reasons.

2022-08-17 17:21 UTC, mickael-menu commented on navigator/src/epub/EpubNavigator.ts
> +}
Some of these APIs will need to be moved to a shared `NavigatorListener` interface. But this can be addressed in another PR.

2022-08-17 17:21 UTC, mickael-menu commented on navigator-html-injectables/src/modules/snapper/Snapper.ts
> +        bstyle.userSelect = "none";
This will probably conflict with the (future) highlighting feature which requires being able to select the text.

```suggestion
```

2022-10-19 11:49 UTC, dysbulic commented on navigator/src/epub/EpubNavigator.ts
> +        this.apply().then(() => cb());
```suggestion
        this.apply().then(cb);
```

2022-10-19 11:50 UTC, dysbulic commented on navigator/src/epub/frame/FrameManager.ts
> +    async show(atProgress: number | undefined = undefined): Promise<void> {
```suggestion
    async show(atProgress?: number): Promise<void> {
```

2022-10-19 11:51 UTC, dysbulic commented on navigator/src/epub/frame/FrameManager.ts
> +                if(atProgress && atProgress > 0) {
`undefined > 0 === false`, so if the compiler will allow it, this could just be:

 ```suggestion
                if(atProgress > 0) {
```

2022-10-19 11:54 UTC, dysbulic commented on navigator/src/epub/frame/FrameManager.ts
> +                }
```suggestion
                const remove = () => {
                  this.frame.style.removeProperty("visibility");
                  this.frame.style.removeProperty("opacity");
                  this.frame.style.removeProperty("pointer-events");
                  res();
                }
                if(atProgress && atProgress > 0) {
                    this.comms?.send("go_progression", atProgress, remove);
                } else {
                  remove()
                }
```

2022-10-19 11:55 UTC, dysbulic commented on navigator/src/epub/frame/FramePoolManager.ts
> +                const hasProgression = !isNaN(locator.locations.progression as number) && locator.locations.progression! > 0;
```suggestion
                const hasProgression = locator?.locations?.progression > 0;
```

2022-10-28 00:16 UTC, chocolatkey commented on navigator/src/epub/frame/FrameManager.ts
> +    async show(atProgress: number | undefined = undefined): Promise<void> {
👍

2022-10-28 00:16 UTC, chocolatkey commented on navigator/src/epub/frame/FrameManager.ts
> +                if(atProgress && atProgress > 0) {
![image](https://user-images.githubusercontent.com/13407784/198420763-2714f22e-e717-4816-bb85-974094acf3b4.png)
The compiler doesn't like it, I'll leave it for now

2022-10-28 00:19 UTC, chocolatkey commented on navigator/src/epub/frame/FrameManager.ts
> +                }
👍

2022-10-28 00:24 UTC, chocolatkey commented on navigator/src/epub/frame/FramePoolManager.ts
> +                const hasProgression = !isNaN(locator.locations.progression as number) && locator.locations.progression! > 0;
Still could be undefined, but I'm adding `?? 0` to fix that

2022-10-28 00:38 UTC, chocolatkey commented on navigator-html-injectables/src/Loader.ts
> +                console.warn(`Module "${name} does not exist in the library"`)
👍

2022-10-28 00:41 UTC, chocolatkey commented on navigator-html-injectables/src/Loader.ts
> +        if(!nm.mount(this.wnd, this.comms)) return false; // Mount module
👍

2022-10-28 00:49 UTC, chocolatkey commented on navigator-html-injectables/src/modules/Module.ts
> +}
👍

2022-10-28 00:56 UTC, chocolatkey commented on navigator/src/Navigator.ts
> +    abstract goLink(link: Link, animated: boolean, cb: cbv): void;
👍

2022-10-28 00:57 UTC, chocolatkey commented on navigator/src/Navigator.ts
> +     goRight(animated = false, completion: cbv) {
👍

2022-10-28 00:59 UTC, chocolatkey commented on navigator/src/epub/EpubNavigator.ts
> +    public get cframe() {
Good idea

2022-10-28 01:06 UTC, chocolatkey commented on navigator-html-injectables/src/comms/keys.ts
> +    "exact_progress";
I'll work on this in a future PR

2022-10-28 01:24 UTC, chocolatkey commented on navigator/src/epub/frame/FramePoolManager.ts
> +export default class FramePoolManager {
I've added a FrameBlobBuider class for now. I'll use the factory approach when we have more types

2022-10-28 01:26 UTC, chocolatkey commented on navigator/src/epub/EpubNavigator.ts
> +                    else if (edata.x > oneQuarter * 3) this.goRight(false, () => { }); // Go right if right quarter clicked
I'll handle this in an independent PR as it will break existing consumers of the toolkit

2022-10-28 01:26 UTC, chocolatkey commented on navigator/src/epub/frame/FramePoolManager.ts
> +const LOWER_BOUNDARY = 3;
👍

2022-10-31 13:20 UTC, mickael-menu commented on navigator-html-injectables/src/comms/keys.ts
> +    "exact_progress";
Alright

2022-10-31 14:03 UTC, mickael-menu approved these changes
There are some pending comments that you can review, but nothing preventing this PR from being merged.

2022-10-31 14:03 UTC, mickael-menu commented on navigator/src/epub/frame/FrameBlobBuilder.ts
> +const READIUM_CSS_PATH = "https://cdn.jsdelivr.net/gh/readium/readium-css@583011453612e6f695056ab6c086a2c4f4cac9c0/css/dist/{FILE}";
FYI eventually apps should be able to provide their own build of Readium CSS, as it is customizable at build time.

2022-10-31 14:03 UTC, mickael-menu commented on navigator/src/epub/EpubNavigator.ts
> +            modules = modules.filter((m) => m !== "scroll_snapper");
It will be relevant for a future PR, but FYI:
* reading progression will have only for possible values LTR and RTL
* to determine whether we scroll or paginate, there will be a setting `scroll: bool`
* we'll have an additional `scrollAxis: horizontal | vertical` setting to support CJK in horizontal scroll mode

2022-10-31 14:03 UTC, mickael-menu commented on navigator-html-injectables/src/modules/ReflowablePeripherals.ts
> +        event.preventDefault(); // TODO when not to prevent?
Are you able to get a bool result from the tap/click events? Then you can delegate this choice to the app.

See https://github.com/readium/kotlin-toolkit/blob/e5231436cac3a802fb5e406eda63bce4f1a5549d/readium/navigator/src/main/assets/_scripts/src/gestures.js#L33-L40

2022-11-01 01:04 UTC, chocolatkey commented on navigator/src/epub/frame/FrameBlobBuilder.ts
> +const READIUM_CSS_PATH = "https://cdn.jsdelivr.net/gh/readium/readium-css@583011453612e6f695056ab6c086a2c4f4cac9c0/css/dist/{FILE}";
Yeah, in my local copy I have readium CSS as a submodule, I'm still deciding on the best way to integrate it. This is just a temporary solution, definitely shouldn't be including like this in the final vers, e.g. prevents offline reading

2022-11-01 01:05 UTC, chocolatkey commented on navigator/src/epub/EpubNavigator.ts
> +            modules = modules.filter((m) => m !== "scroll_snapper");
OK, @mickael-menu can you link me to where those changes were discussed for other toolkits/spec?

2022-11-01 01:09 UTC, chocolatkey commented on navigator-html-injectables/src/modules/ReflowablePeripherals.ts
> +        event.preventDefault(); // TODO when not to prevent?
That can't be done unfortunately because you can't make the browser wait for completion of an async function **before** calling preventDefault(). Since the injectables communicate with an async message to send the event, and then another back that would contain the bool you speak of, the event will have already happened and will no longer be preventable. I'm still thinking of a solution, suggestions welcome.

2022-11-01 01:10 UTC, merged