Radium Shared Models recoded from scratch
readium/ts-toolkit pull request #8
Opened 2021-07-29 13:52 UTC by bilal-uslu

2021-08-05 09:26 UTC, mickael-menu requested changes
Overall great changes!

2021-08-05 09:26 UTC, mickael-menu commented on .github/workflows/CI-shared-model.yml
> +name: CI-shared-models
👍 for adding a CI workflow

That raises the question: how should we handle the GitHub workflows for all the packages in the monorepo?

* A single workflow with one job per package (my preference)
* One workflow per package (like here)

There will be a lot of duplication, but maybe GitHub actions allow to reuse some of the steps among jobs.

2021-08-05 09:26 UTC, mickael-menu commented on .github/workflows/size-shared-model.yml
> +name: size-shared-model
What is this workflow used for?

2021-08-05 09:26 UTC, mickael-menu commented on .gitignore
> +example/build/jellybookslib.js
We'll need to sort out every occurrence of Jellybooks specific mentions.

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/package.json
> +  "name": "@jellybooks/shared-test",
Another question for a call: how to organize the packages in the repo?

`shared-models` doesn't match other platforms, and it won't necessarily contain only models so we could rename it to only `shared`.

However we could also embrace the monorepo and make many smaller packages, so I would split `shared-models` into:
* `opds` – all models and parsers related to OPDS
* `publication` or `pub`  – the shared `Publication` models as well as publication service definitions and their default implementation
* `mediatype` – the media type definitions and sniffers

This is the approach we are taking in `go-toolkit`.

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/LocatorCollection.ts
> +export class LocatorMetadata {
If we can't have a nested `LocatorCollection.Metadata` type, then maybe we should rename this into `LocatorCollectionMetadata`? On first read, I was confused as I thought this was the metadata of a single `Locator` object.

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/BelongsTo.ts
> +/* Copyright 2021 Readium Foundation. All rights reserved.
I know the project had some capitalized folders as well before this PR so it's not a comment for it in particular. But this doesn't seem to be a standard convention. Should we change everything to lowercase?

<img width="229" alt="Screenshot 2021-08-05 at 10 03 44" src="https://user-images.githubusercontent.com/58686775/128314385-f42f67c7-aa88-455c-a2a6-8ec664e42a49.png">

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Link.ts
> +
We can put `Link` properties as `readonly` as well, unless you had a specific need in mind for mutability?

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Link.ts
> +  public rels?: Set<string>;
I guess having list/set properties as nullable is fine. On mobile we avoided nullability except for litteral values to simplify calling code:

```typescript
link.rels.contains("cover")
```

vs

```typescript
link.rels?.contains("cover") == true
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Link.ts
> +  public getMediaType(): MediaType {
The sniffing of a  `Link` media type will be really fast since it's only comparing `type`, so I think a getter would be nicer here to hide the fact it's a computed property:

```suggestion
  public get mediaType(): MediaType {
```

I like to use this convention: use a property/getter when:

* it's semantically a field
* it doesn't have any side effect
* it returns relatively quickly and so can be called from the UI thread

Otherwise I use a method.

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Link.ts
> +  public toAbsoluteHREF(baseUrl?: string): string | undefined {
We name it `toURL()` on other platforms

```suggestion
  public toURL(baseUrl?: string): string | undefined {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Link.ts
> +  public getTemplateParameters(): Set<string> {
```suggestion
  public get templateParameters(): Set<string> {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Link.ts
> +  public toLocator(): Locator {
```suggestion
  public get locator(): Locator {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Locator.ts
> +export class Text {
```suggestion
export class LocatorText {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Locator.ts
> +export class Locations {
If we can't have a `Locator.` namespace in Typescript, lets prefix the types.

```suggestion
export class LocatorLocations {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Locator.ts
> +  public fragments: Array<string>;
The `Locator` properties can be `readonly` as well.

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Locator.ts
> +  // cssSelector?: string;
Yeah I think we can remove this altogether. It can always be implemented in `otherLocations`.

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Locator.ts
> +  public copyWithLocations(values: any): Locator {
I don't know much TypeScript, but feel free to adapt this kind of code to what you would usually find in TypeScript native libs. If there's an easier way to modify an immutable object.

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Manifest.ts
> +  public setSelfLink(href: string): void {
I think this won't be needed for Readium Web, it was because of the internal HTTP server on mobile.

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Manifest.ts
> +  public getBaseURL(): string | undefined {
```suggestion
  public get baseURL(): string | undefined {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Metadata.ts
>    public effectiveReadingProgression(): ReadingProgression {
```suggestion
  public get effectiveReadingProgression(): ReadingProgression {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/BelongsTo.ts
> +export class BelongsTo {
I'm not sure we need a dedicated `BelongsTo` object, but maybe it's easier in the TypeScript codebase.

On mobile we have `Metadata.belongsTo: Map<String, [Collection]>`.

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/BelongsTo.ts
> +  public readonly items: Map<string, Contributors>;
The term `Contributor` is a bit confusing in this context. Since it's basically the same object, we added a typealias on mobile. Is is something feasible with TypeScript?

```
public typealias Collection = Contributor
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Publication.ts
> +  public setSelfLink(href: string): void {
I think this won't be needed for Readium Web.

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Publication.ts
> +  public getType(): PublicationType {
`PublicationType` was some legacy code in mobile, and we will deprecate it soon. So I think we don't need it for Web.

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/Publication.ts
> +  public getBaseURL(): string | undefined {
```suggestion
  public get baseURL(): string | undefined {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/PublicationCollection.ts
> +  public static collectionsFromJSON(
Maybe `deserializeCollections()`?

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/encryption/Properties.ts
> +};
Extensions seem really easy with TypeScript as well!

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/epub/EpubLayout.ts
> +export enum EpubLayout {
Isn't the convention to keep accronyms as uppercase?

```suggestion
export enum EPUBLayout {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/Publication/epub/Properties.ts
> +    getContains(): Set<string> | undefined;
Is it possible to have getters as an extension?

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/util/mediatype/MediaType.ts
> +  public isJson(): boolean {
```suggestion
  public isJSON(): boolean {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/util/mediatype/MediaType.ts
> +  public isOpds(): boolean {
```suggestion
  public isOPDS(): boolean {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/util/mediatype/MediaType.ts
> +  public isHtml(): boolean {
```suggestion
  public isHTML(): boolean {
```

2021-08-05 09:26 UTC, mickael-menu commented on shared-models/src/util/mediatype/MediaType.ts
> +  public isZIP(): boolean {
```suggestion
  public get isZIP(): boolean {
```

2021-08-05 12:52 UTC, bilal-uslu commented on .github/workflows/CI-shared-model.yml
> +name: CI-shared-models
There is a filter,
for the specific package,
but still i would prefer keep shared models and navigator package in seperate repos, It does not make sense to me have all in a single repo, since there is no significance advantage

name: CI-shared-models
on: 
  push:
    paths:
      - 'shared-models/**'
      - '.github/workflows/CI-shared-models.yml'

2021-08-05 12:53 UTC, bilal-uslu commented on .github/workflows/size-shared-model.yml
> +name: size-shared-model
to keep the created package in a specific size, too prevent publishing of a huge size of a library

2021-08-05 12:59 UTC, bilal-uslu commented on shared-models/package.json
> +  "name": "@jellybooks/shared-test",
if we are going to publish it on npm as a package then we should keep them together. Otherwise there may be too much npm packages

2021-08-05 14:28 UTC, mickael-menu commented on .github/workflows/CI-shared-model.yml
> +name: CI-shared-models
We've already decided to go with monorepos for all the reasons explained in this discussion: https://github.com/readium/architecture/discussions/136

Believe me we have the experience of multiple repos with the Readium architecture and it's a pain to maintain.

2021-08-05 14:31 UTC, mickael-menu commented on .github/workflows/CI-shared-model.yml
> +name: CI-shared-models
Although feel free to chime in in this discussion after taking a look at the arguments with some counter-arguments specific to Readium Web.

2021-08-05 16:53 UTC, mickael-menu commented on .github/workflows/CI-shared-model.yml
> +name: CI-shared-models
By the way, I think clarifying what will the navigator provide could help too. We want to provide a very simple API that has no user interface. Basically something like `Navigator(containerElement)`, and then it will create the iframes and handle the scrolling inside the container. There won't be any progression bar or "bookmark page" button, for example. And the navigator won't depend on any high-level UI framework (React, Vue.js, etc.)

Then, each implementer will have their own repo to create the actual reader user interface using whatever UI framework they want and using Readium's navigator only for the "rendering" component/view.

Readium will also provide a set of interfaces that Navigator implementations will need to implement. This way a reading app using these interfaces can switch to a different navigator implementation (maybe not provided by Readium) without changing any of their app code.

Does having the navigator interfaces and default implementations in the mono-repo makes more sense for you in this context?

2021-08-05 22:44 UTC, bilal-uslu commented on .github/workflows/CI-shared-model.yml
> +name: CI-shared-models
Ok. It is more clear now.

2021-08-06 01:13 UTC, bilal-uslu commented on .gitignore
> +example/build/jellybookslib.js
removed

2021-08-06 08:03 UTC, bilal-uslu commented on shared-models/package.json
> +  "name": "@jellybooks/shared-test",
changed shared-models to shared

2021-08-06 08:03 UTC, bilal-uslu commented on shared-models/src/Publication/LocatorCollection.ts
> +export class LocatorMetadata {
renamed

2021-08-06 08:04 UTC, bilal-uslu commented on shared-models/src/Publication/BelongsTo.ts
> +/* Copyright 2021 Readium Foundation. All rights reserved.
changed

2021-08-06 08:04 UTC, bilal-uslu commented on shared-models/src/Publication/Link.ts
> +
done

2021-08-06 08:06 UTC, bilal-uslu commented on shared-models/src/Publication/Link.ts
> +  public rels?: Set<string>;
for serialization and deserialization it is better to keep like that. by the way it is a reasonable usage for typescript and javascript

2021-08-06 08:06 UTC, bilal-uslu commented on shared-models/src/Publication/Link.ts
> +  public getMediaType(): MediaType {
done

2021-08-06 08:06 UTC, bilal-uslu commented on shared-models/src/Publication/Link.ts
> +  public toAbsoluteHREF(baseUrl?: string): string | undefined {
done

2021-08-06 08:06 UTC, bilal-uslu commented on shared-models/src/Publication/Link.ts
> +  public getTemplateParameters(): Set<string> {
done

2021-08-06 08:06 UTC, bilal-uslu commented on shared-models/src/Publication/Link.ts
> +  public toLocator(): Locator {
done

2021-08-06 08:06 UTC, bilal-uslu commented on shared-models/src/Publication/Locator.ts
> +export class Text {
renamed

2021-08-06 08:06 UTC, bilal-uslu commented on shared-models/src/Publication/Locator.ts
> +export class Locations {
renamed

2021-08-06 08:06 UTC, bilal-uslu commented on shared-models/src/Publication/Locator.ts
> +  public fragments: Array<string>;
done

2021-08-06 08:07 UTC, bilal-uslu commented on shared-models/src/Publication/Locator.ts
> +  // cssSelector?: string;
removed

2021-08-06 08:07 UTC, bilal-uslu commented on shared-models/src/Publication/Locator.ts
> +  public copyWithLocations(values: any): Locator {
simplified

2021-08-06 08:07 UTC, bilal-uslu commented on shared-models/src/Publication/Manifest.ts
> +  public setSelfLink(href: string): void {
removed

2021-08-06 08:16 UTC, bilal-uslu commented on shared-models/src/Publication/Manifest.ts
> +  public getBaseURL(): string | undefined {
done

2021-08-06 08:16 UTC, bilal-uslu commented on shared-models/src/Publication/Metadata.ts
>    public effectiveReadingProgression(): ReadingProgression {
done

2021-08-06 08:16 UTC, bilal-uslu commented on shared-models/src/Publication/BelongsTo.ts
> +export class BelongsTo {
yes. this way is easier

2021-08-06 08:17 UTC, bilal-uslu commented on shared-models/src/Publication/BelongsTo.ts
> +  public readonly items: Map<string, Contributors>;
yes, we can. I have aliased it to Collection

2021-08-06 08:17 UTC, bilal-uslu commented on shared-models/src/Publication/Publication.ts
> +  public setSelfLink(href: string): void {
removed

2021-08-06 08:17 UTC, bilal-uslu commented on shared-models/src/Publication/Publication.ts
> +  public getType(): PublicationType {
removed

2021-08-06 08:17 UTC, bilal-uslu commented on shared-models/src/Publication/Publication.ts
> +  public getBaseURL(): string | undefined {
done

2021-08-06 08:17 UTC, bilal-uslu commented on shared-models/src/Publication/PublicationCollection.ts
> +  public static collectionsFromJSON(
good point, renamed,

2021-08-06 08:18 UTC, bilal-uslu commented on shared-models/src/Publication/encryption/Properties.ts
> +};
yes exactly, to setup this part was a bit painful, but looks good now

2021-08-06 08:19 UTC, bilal-uslu commented on shared-models/src/Publication/epub/EpubLayout.ts
> +export enum EpubLayout {
renamed

2021-08-06 08:19 UTC, bilal-uslu commented on shared-models/src/Publication/epub/Properties.ts
> +    getContains(): Set<string> | undefined;
yes, done

2021-08-06 08:19 UTC, bilal-uslu commented on shared-models/src/util/mediatype/MediaType.ts
> +  public isJson(): boolean {
renamed

2021-08-06 08:19 UTC, bilal-uslu commented on shared-models/src/util/mediatype/MediaType.ts
> +  public isOpds(): boolean {
renamed

2021-08-06 08:20 UTC, bilal-uslu commented on shared-models/src/util/mediatype/MediaType.ts
> +  public isHtml(): boolean {
renamed

2021-08-06 08:20 UTC, bilal-uslu commented on shared-models/src/util/mediatype/MediaType.ts
> +  public isZIP(): boolean {
done

2021-08-09 11:48 UTC, mickael-menu commented on shared-models/src/Publication/Link.ts
> +  public rels?: Set<string>;
Alright

2021-08-09 12:01 UTC, mickael-menu requested changes
Mostly fine, there's a couple of suggestions left.

Also could you rename the `shared-models` folder into just `shared`? Thanks.

2021-08-09 12:01 UTC, mickael-menu commented on shared-models/src/publication/Publication.ts
> +}
We can remove this enum now.

2021-08-09 12:01 UTC, mickael-menu commented on shared-models/src/publication/Locator.ts
> +  public highlight?: string;
```suggestion
  public readonly after?: string;
  public readonly before?: string;
  public readonly highlight?: string;
```

2021-08-09 12:01 UTC, mickael-menu commented on shared-models/src/publication/Locator.ts
> +  public text?: LocatorText;
```suggestion
  public readonly href: string;

  /** The media type of the resource that the Locator Object points to. */
  public readonly type: string;

  /** The title of the chapter or section which is more relevant in the context of this locator. */
  public readonly title?: string;

  /** One or more alternative expressions of the location. */
  public readonly locations: LocatorLocations;

  /** Textual context of the locator. */
  public readonly text?: LocatorText;
```

2021-08-09 12:01 UTC, mickael-menu commented on shared-models/src/util/mediatype/MediaType.ts
> +  public get isRwpm(): boolean {
```suggestion
  public get isRWPM(): boolean {
```

2021-08-09 13:00 UTC, bilal-uslu commented on shared-models/src/publication/Publication.ts
> +}
removed

2021-08-09 13:00 UTC, bilal-uslu commented on shared-models/src/publication/Locator.ts
> +  public highlight?: string;
done

2021-08-09 13:00 UTC, bilal-uslu commented on shared-models/src/publication/Locator.ts
> +  public text?: LocatorText;
done

2021-08-09 13:16 UTC, bilal-uslu commented on shared-models/src/util/mediatype/MediaType.ts
> +  public get isRwpm(): boolean {
renamed

2021-08-09 15:42 UTC, mickael-menu approved these changes

2021-08-09 15:55 UTC, mickael-menu commented
I'm not sure the GitHub actions will trigger until we merge this PR in, as you are not maintainer on the repo.

2021-08-09 16:14 UTC, dysbulic commented on shared/src/publication/Link.ts
> +        return el.mediaType.matches(mediaType);
I'm pretty sure this will only check the first element of the array. You need to only `return` if it's found.

```suggestion
        if (el.mediaType.matches(mediaType)) {
          return true;
        }
```

2021-08-09 16:25 UTC, dysbulic commented on shared/src/publication/Locator.ts
> +      position: position !== undefined && position > 0 ? position : undefined,
`undefined > 0` is `false`, so you can just put:

```suggestion
      position: position > 0 ? position : undefined,
```

2021-08-09 16:27 UTC, bilal-uslu commented on shared/src/publication/Link.ts
> +        return el.mediaType.matches(mediaType);
good point. fixed. thanks

2021-08-09 16:28 UTC, dysbulic commented on shared/src/publication/Locator.ts
> +    if (this.title !== undefined) json.title = this.title;
As a pattern in your serializer functions, it is safe to assign `undefined` to variables that are already `undefined`, so you can remove many of your `if` guards.

```suggestion
    json.title = this.title;
```

2021-08-09 16:33 UTC, dysbulic commented on shared/src/publication/Manifest.ts
> +          li === -1 ? undefined : href.substring(href.lastIndexOf('/') + 1);
```suggestion
          li === -1 ? undefined : href.substring(li + 1);
```

2021-08-09 16:39 UTC, dysbulic commented on shared/src/publication/Manifest.ts
> +      el => el.rels && el.rels.has('self')
```suggestion
      el => el.rels && el.rels.has('self')
      el => el.rels?.has?.('self')
```

2021-08-09 16:41 UTC, dysbulic commented on shared/src/publication/Manifest.ts
> +      let href = selfLink.href;
Remove the `if (selfLink) {` statement and just have:

```suggestion
      let href = selfLink?.href;
```

2021-08-09 16:59 UTC, dysbulic commented on shared/src/publication/Metadata.ts
> +    if (this.subtitle) json.subtitle = this.subtitle.serialize();
Another pattern that allows you to remove more of your `if` guards is the use of the [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operator:

```suggestion
    json.subtitle = this.subtitle?.serialize();
```

2021-08-09 17:00 UTC, dysbulic commented on shared/src/publication/Publication.ts
> +    return list && list.length > 0 ? list[0].links : undefined;
```suggestion
    return list?.[0]?.links;
```

2021-08-09 17:03 UTC, dysbulic commented on shared/src/opds/Acquisition.ts
> +    if (!(json && json.type)) return;
```suggestion
    if (!json?.type) return;
```

2021-08-09 17:11 UTC, dysbulic commented on shared/src/util/JSONParse.ts
> +  return json && json instanceof Array ? json : undefined;
`undefined instanceof Array` (or `null` or `0` or any falsey value) is `false`, so you just need: 

```suggestion
  return json instanceof Array ? json : undefined;
```

2021-08-09 17:13 UTC, dysbulic commented on shared/src/util/URITemplate.ts
> +          const parameterValue = parameters[parameter];
```suggestion
          const parameterValue = parameters[parameter] ?? '';
```

2021-08-09 17:13 UTC, dysbulic commented on shared/src/util/URITemplate.ts
> +          return parameterValue ? encodeURIComponent(parameterValue) : '';
```suggestion
          return encodeURIComponent(parameterValue);
```

2021-08-12 16:07 UTC, merged